[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "chromium"]

[phases.install]
cmds = [
  "pip install --break-system-packages -r requirements.txt",
  "python3 -m playwright install --with-deps chromium"
]
